#!/usr/bin/env python3
"""
Arcturian Grid — 81-Channel Template Generator
================================================
Reads nodes.yaml (9 domains) and layers.yaml (9 depths),
calls a local LLM via Ollama to generate contextually appropriate
prompt templates for each of the 81 intersections.

Usage:
    python generate_grid.py                    # Generate all 81
    python generate_grid.py --dry-run          # No LLM calls
    python generate_grid.py --regenerate --corrections corrections.yaml
    python generate_grid.py --nodes ANCHOR,PULSE --layers PERCEPTION,WISDOM
    python generate_grid.py --model gemma3:27b
    python generate_grid.py --show-seeds
    python generate_grid.py --retry-broken     # Re-generate only broken templates

Stream: NEURO (Neurogenesis)
Phase: N4-N5
Author: Ka'tuar'el
"""

import argparse
import json
import os
import re
import sys
import time
from datetime import datetime
from pathlib import Path

import requests
import yaml


# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

SCRIPT_DIR = Path(__file__).parent.resolve()
DEFAULT_NODES = SCRIPT_DIR / "nodes.yaml"
DEFAULT_LAYERS = SCRIPT_DIR / "layers.yaml"
DEFAULT_OUTPUT = SCRIPT_DIR / "templates"
DEFAULT_MODEL = os.getenv("OLLAMA_MODEL", "qwen3:30b-a3b")
OLLAMA_CHAT_URL = "http://localhost:11434/api/chat"

MIN_PROMPT_LENGTH = 100

MODEL_TIER_MAP = {
    "small": ["mistral:7b", "qwen2.5:7b", "nous-hermes2:latest"],
    "medium": ["phi4:14b", "qwen3:14b", "mistral-small:24b"],
    "large": ["gemma3:27b", "iris-thinking-v2:latest", "command-r:35b"],
}

PROCESSING_MAP = {
    1: {"processing": "unconscious", "critical_path": False},
    2: {"processing": "unconscious", "critical_path": False},
    3: {"processing": "conscious", "critical_path": False},
    4: {"processing": "conscious", "critical_path": False},
    5: {"processing": "conscious", "critical_path": True},
    6: {"processing": "conscious", "critical_path": True},
    7: {"processing": "deep_conscious", "critical_path": False},
    8: {"processing": "deep_conscious", "critical_path": False},
    9: {"processing": "deep_conscious", "critical_path": True},
}


# ---------------------------------------------------------------------------
# Deterministic Schemas (NOT generated by LLM — always correct)
# ---------------------------------------------------------------------------

BASE_SCHEMA_FIELDS = {
    "summary": {"type": "string", "description": "1-2 sentence summary of analysis"},
    "confidence": {"type": "number", "minimum": 0, "maximum": 1},
    "flags": {"type": "array", "items": {"type": "string"}, "description": "Notable findings"},
}

NODE_SCHEMA_FIELDS = {
    "ANCHOR": {
        "locations": {"type": "array", "items": {"type": "string"}},
        "times": {"type": "array", "items": {"type": "string"}},
        "people": {"type": "array", "items": {"type": "string"}},
        "objects": {"type": "array", "items": {"type": "string"}},
        "actions": {"type": "array", "items": {"type": "string"}},
        "environment": {"type": "string"},
    },
    "ECHO": {
        "matched_patterns": {"type": "array", "items": {"type": "string"}},
        "recurring_themes": {"type": "array", "items": {"type": "string"}},
        "cycle_indicators": {"type": "array", "items": {"type": "string"}},
        "echo_strength": {"type": "number", "minimum": 0, "maximum": 1},
    },
    "PULSE": {
        "primary_emotion": {"type": "string"},
        "secondary_emotions": {"type": "array", "items": {"type": "string"}},
        "energy_level": {"type": "string", "enum": ["very_low", "low", "medium", "high", "very_high"]},
        "energy_direction": {"type": "string", "enum": ["rising", "stable", "falling"]},
        "tension_points": {"type": "array", "items": {"type": "string"}},
    },
    "LENS": {
        "frameworks_applied": {"type": "array", "items": {"type": "string"}},
        "interpretations": {"type": "array", "items": {"type": "object"}},
        "primary_framework": {"type": "string"},
    },
    "BEACON": {
        "relevant_facts": {"type": "array", "items": {"type": "string"}},
        "data_points": {"type": "array", "items": {"type": "object"}},
        "knowledge_gaps": {"type": "array", "items": {"type": "string"}},
    },
    "WEAVE": {
        "connections": {"type": "array", "items": {"type": "object"}},
        "active_threads": {"type": "array", "items": {"type": "string"}},
        "relationship_dynamics": {"type": "array", "items": {"type": "string"}},
    },
    "MIRROR": {
        "user_reveals": {"type": "array", "items": {"type": "string"}},
        "iris_notices": {"type": "array", "items": {"type": "string"}},
        "blind_spots": {"type": "array", "items": {"type": "string"}},
        "projections": {"type": "array", "items": {"type": "string"}},
    },
    "COMPASS": {
        "stated_need": {"type": "string"},
        "actual_need": {"type": "string"},
        "recommended_action": {"type": "string"},
        "trajectory": {"type": "string"},
    },
    "GATEWAY": {
        "spiritual_dimension": {"type": "string"},
        "lineage_echoes": {"type": "array", "items": {"type": "string"}},
        "synchronicities": {"type": "array", "items": {"type": "string"}},
        "transcendent_read": {"type": "string"},
    },
}


def build_schema(node_id: str) -> dict:
    """Build output schema deterministically. No LLM needed."""
    props = dict(BASE_SCHEMA_FIELDS)
    props.update(NODE_SCHEMA_FIELDS.get(node_id, {}))
    return {
        "type": "object",
        "properties": props,
        "required": ["summary", "confidence", "flags"],
    }


# ---------------------------------------------------------------------------
# YAML Loaders
# ---------------------------------------------------------------------------

def load_nodes(path: Path) -> list[dict]:
    with open(path) as f:
        return yaml.safe_load(f)["nodes"]


def load_layers(path: Path) -> list[dict]:
    with open(path) as f:
        return yaml.safe_load(f)["layers"]


def load_corrections(path: Path) -> list[dict]:
    if not path or not path.exists():
        return []
    with open(path) as f:
        data = yaml.safe_load(f)
    return data.get("corrections", []) if data else []


# ---------------------------------------------------------------------------
# Correction Engine
# ---------------------------------------------------------------------------

def get_applicable_corrections(corrections, node_id, layer_id, function_id, model_tier):
    applicable = []
    for c in corrections:
        target = c.get("applies_to", "")
        rule = c.get("rule", "")
        if not rule:
            continue
        if target == "all":
            applicable.append(rule)
        elif target.startswith("node:") and target.split(":")[1] == node_id:
            applicable.append(rule)
        elif target.startswith("layer:") and target.split(":")[1] == layer_id:
            applicable.append(rule)
        elif target.startswith("function:") and target.split(":")[1] == function_id:
            applicable.append(rule)
        elif target.startswith("model_tier:") and target.split(":")[1] == model_tier:
            applicable.append(rule)
    return applicable


# ---------------------------------------------------------------------------
# Meta-Prompt — asks LLM for ONLY the prompt text, as JSON
# ---------------------------------------------------------------------------

def build_meta_prompt(node: dict, layer: dict, corrections: list[str]) -> str:
    focus_areas = "\n".join(f"  - {fa}" for fa in node.get("focus_areas", []))

    word_limit = "under 150 words" if layer["model_tier"] == "small" else \
                 "under 250 words" if layer["model_tier"] == "medium" else \
                 "under 350 words"

    correction_block = ""
    if corrections:
        rules = "\n".join(f"  - {r}" for r in corrections)
        correction_block = f"""
MANDATORY RULES for the prompt you generate:
{rules}
"""

    return f"""Write an LLM prompt template for a consciousness architecture processing function.

This function analyzes conversation exchanges at the intersection of:
- NODE: {node['name']} — {node['domain']}
- LAYER: {layer['name']} (depth {layer['depth']}) — {layer['instruction']}

The node asks: "{node['core_question']}"
The node focuses on:
{focus_areas}

The layer instruction: "{layer['instruction']}"
Output style: {layer['output_style']}

Node example output: "{node.get('example_output', 'N/A')}"
{correction_block}
Requirements for the prompt you write:
- It must instruct an LLM to analyze a conversation exchange
- It must include the literal text {{user_message}} and {{assistant_response}} as placeholders
- It must tell the LLM to respond with JSON only
- It must be {word_limit}
- It must focus ONLY on this specific node+layer intersection
- It must match the output style: {layer['output_style']}

Respond with ONLY a JSON object containing one key "prompt" whose value is the prompt template string.
No markdown. No backticks. No explanation. Just the JSON object.

Example: {{"prompt": "Analyze the following conversation exchange and extract all physical details..."}}"""


# ---------------------------------------------------------------------------
# LLM Caller
# ---------------------------------------------------------------------------

def call_ollama(prompt: str, model: str) -> str:
    """Call Ollama chat endpoint, return content string."""
    try:
        resp = requests.post(
            OLLAMA_CHAT_URL,
            json={
                "model": model,
                "messages": [
                    {
                        "role": "system",
                        "content": (
                            "You are a JSON generator. You respond with ONLY valid JSON objects. "
                            "No markdown, no backticks, no explanation, no preamble. "
                            "Just the raw JSON object starting with { and ending with }."
                        ),
                    },
                    {"role": "user", "content": prompt},
                ],
                "stream": False,
                "options": {
                    "temperature": 0.7,
                    "top_p": 0.9,
                    "num_predict": 2048,
                },
            },
            timeout=120,
        )
        resp.raise_for_status()
        data = resp.json()
        msg = data.get("message", {})
        result = msg.get("content", "")
        if not result and isinstance(msg, dict):
            result = msg.get("thinking", "")
        return result
    except requests.exceptions.ConnectionError:
        print(f"  ✗ Cannot connect to Ollama at {OLLAMA_CHAT_URL}")
        print("    Is Ollama running? Try: ollama serve")
        sys.exit(1)
    except requests.exceptions.Timeout:
        print("  ✗ Timed out after 120s")
        return ""
    except Exception as e:
        print(f"  ✗ Ollama error: {e}")
        return ""


# ---------------------------------------------------------------------------
# JSON Response Parser
# ---------------------------------------------------------------------------

def extract_prompt_from_response(raw: str) -> str:
    """Extract the prompt string from the LLM's JSON response."""
    if not raw:
        return ""

    cleaned = raw.strip()
    cleaned = re.sub(r'^```(?:json)?\s*', '', cleaned)
    cleaned = re.sub(r'\s*```$', '', cleaned)
    cleaned = cleaned.strip()

    # Strategy 1: Direct JSON parse
    try:
        data = json.loads(cleaned)
        if isinstance(data, dict) and "prompt" in data:
            return data["prompt"]
    except json.JSONDecodeError:
        pass

    # Strategy 2: Find outermost { } and parse
    start = cleaned.find("{")
    end = cleaned.rfind("}")
    if start >= 0 and end > start:
        try:
            data = json.loads(cleaned[start:end + 1])
            if isinstance(data, dict) and "prompt" in data:
                return data["prompt"]
        except json.JSONDecodeError:
            pass

    # Strategy 3: Regex for "prompt": "..."
    match = re.search(r'"prompt"\s*:\s*"((?:[^"\\]|\\.)*)"', cleaned, re.DOTALL)
    if match:
        try:
            return json.loads(f'"{match.group(1)}"')
        except (json.JSONDecodeError, ValueError):
            return match.group(1)

    # Strategy 4: If response looks like a usable prompt itself
    if len(cleaned) > MIN_PROMPT_LENGTH and "{user_message}" in cleaned.lower():
        return cleaned

    return ""


# ---------------------------------------------------------------------------
# Fallback Prompt Generator
# ---------------------------------------------------------------------------

def generate_fallback_prompt(node: dict, layer: dict) -> str:
    focus_list = ", ".join(node.get("focus_areas", [])[:3])
    return f"""Analyze the following conversation exchange through the lens of {node['name']} ({node['domain']}) at the {layer['name']} depth.

Your task: {layer['instruction']}

Focus specifically on: {focus_list}

Core question to answer: {node['core_question']}

Exchange:
USER: {{user_message}}
ASSISTANT: {{assistant_response}}

Output style: {layer['output_style']}

Respond with JSON only. No preamble, no markdown."""


# ---------------------------------------------------------------------------
# Template Writer
# ---------------------------------------------------------------------------

def write_template(output_dir, node, layer, prompt_text, schema, generation_model):
    function_id = f"{node['id']}_{layer['id']}"
    proc = PROCESSING_MAP.get(layer["depth"], {"processing": "conscious", "critical_path": False})

    template = {
        "function_id": function_id,
        "node": node["id"],
        "node_name": node["name"],
        "node_domain": node["domain"],
        "layer": layer["id"],
        "layer_name": layer["name"],
        "depth": layer["depth"],
        "model_tier": layer["model_tier"],
        "runtime_models": MODEL_TIER_MAP.get(layer["model_tier"], []),
        "processing": proc["processing"],
        "critical_path": proc["critical_path"],
        "generated_at": datetime.now().isoformat(),
        "generated_by": generation_model,
        "prompt": prompt_text,
        "output_schema": schema,
    }

    filepath = output_dir / f"{function_id}.yaml"
    with open(filepath, "w") as f:
        f.write(f"# AUTO-GENERATED — Arcturian Grid Function Template\n")
        f.write(f"# Node: {node['id']} | Layer: {layer['id']} | ID: {function_id}\n")
        f.write(f"# Domain: {node['domain']}\n")
        f.write(f"# Depth: {layer['depth']} ({layer['name']})\n")
        f.write(f"# Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')} | Model: {generation_model}\n")
        f.write(f"# ---\n\n")
        yaml.dump(template, f, default_flow_style=False, sort_keys=False, allow_unicode=True, width=120)

    return filepath


# ---------------------------------------------------------------------------
# Grid Index
# ---------------------------------------------------------------------------

def write_grid_index(output_dir, nodes, layers):
    index = {
        "arcturian_grid": {
            "version": "1.0",
            "generated_at": datetime.now().isoformat(),
            "total_functions": len(nodes) * len(layers),
            "nodes": [n["id"] for n in nodes],
            "layers": [l["id"] for l in layers],
            "matrix": {},
        }
    }
    for node in nodes:
        index["arcturian_grid"]["matrix"][node["id"]] = {}
        for layer in layers:
            fid = f"{node['id']}_{layer['id']}"
            index["arcturian_grid"]["matrix"][node["id"]][layer["id"]] = {
                "function_id": fid,
                "model_tier": layer["model_tier"],
                "processing": PROCESSING_MAP.get(layer["depth"], {}).get("processing", "conscious"),
                "template_file": f"{fid}.yaml",
            }
    filepath = output_dir / "grid_index.yaml"
    with open(filepath, "w") as f:
        f.write("# Arcturian Grid — Function Index\n")
        f.write(f"# Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}\n")
        f.write(f"# Total Functions: {len(nodes) * len(layers)}\n\n")
        yaml.dump(index, f, default_flow_style=False, sort_keys=False, width=120)
    return filepath


# ---------------------------------------------------------------------------
# Broken Template Detection
# ---------------------------------------------------------------------------

def find_broken_templates(output_dir: Path) -> list[tuple[str, str]]:
    """Find templates with prompts shorter than MIN_PROMPT_LENGTH."""
    broken = []
    for f in sorted(output_dir.glob("*.yaml")):
        if f.name == "grid_index.yaml":
            continue
        try:
            with open(f) as fh:
                data = yaml.safe_load(fh)
            prompt = str(data.get("prompt", ""))
            if len(prompt) < MIN_PROMPT_LENGTH:
                broken.append((data["node"], data["layer"]))
        except Exception:
            parts = f.stem.split("_", 1)
            if len(parts) == 2:
                broken.append((parts[0], parts[1]))
    return broken


# ---------------------------------------------------------------------------
# Main Generation Loop
# ---------------------------------------------------------------------------

def generate_grid(
    nodes_path, layers_path, output_dir, model,
    corrections_path=None, filter_nodes=None, filter_layers=None,
    dry_run=False, verbose=False, retry_broken=False, max_retries=3,
):
    print("=" * 60)
    print("  ARCTURIAN GRID — Template Generator")
    print("=" * 60)
    print(f"  Model:       {model}")
    print(f"  Output:      {output_dir}")
    print(f"  Corrections: {corrections_path or 'None'}")
    print(f"  Dry run:     {dry_run}")
    print(f"  Retry mode:  {retry_broken}")
    print(f"  Max retries: {max_retries}")
    print("=" * 60)

    nodes = load_nodes(nodes_path)
    layers = load_layers(layers_path)
    corrections = load_corrections(corrections_path) if corrections_path else []

    node_map = {n["id"]: n for n in nodes}
    layer_map = {l["id"]: l for l in layers}

    if retry_broken:
        cells = find_broken_templates(output_dir)
        print(f"\n  Found {len(cells)} broken templates to retry")
    else:
        if filter_nodes:
            nodes = [n for n in nodes if n["id"] in filter_nodes]
        if filter_layers:
            layers = [l for l in layers if l["id"] in filter_layers]
        cells = [(n["id"], l["id"]) for n in nodes for l in layers]

    total = len(cells)
    if total == 0:
        print("\n  Nothing to generate!")
        return 0, 0

    print(f"  Generating {total} templates")
    if corrections:
        print(f"  Applying {len(corrections)} correction rules")
    print()

    output_dir.mkdir(parents=True, exist_ok=True)

    generated = 0
    failed = 0
    start_time = time.time()
    current_node = None

    for idx, (node_id, layer_id) in enumerate(cells):
        node = node_map[node_id]
        layer = layer_map[layer_id]
        function_id = f"{node_id}_{layer_id}"
        prefix = f"    {idx+1:3d}/{total} {function_id:30s}"

        if node_id != current_node:
            current_node = node_id
            print(f"  [{node_id}]")

        applicable = get_applicable_corrections(
            corrections, node_id, layer_id, function_id, layer["model_tier"]
        )

        schema = build_schema(node_id)

        if dry_run:
            prompt_text = generate_fallback_prompt(node, layer)
            gen_model = "fallback"
        else:
            prompt_text = ""
            gen_model = "fallback"

            for attempt in range(max_retries):
                meta_prompt = build_meta_prompt(node, layer, applicable)
                if verbose:
                    suffix = f" (attempt {attempt+1}/{max_retries})" if attempt > 0 else ""
                    print(f"{prefix} — calling {model}...{suffix}")

                raw = call_ollama(meta_prompt, model)
                prompt_text = extract_prompt_from_response(raw)

                if len(prompt_text) >= MIN_PROMPT_LENGTH:
                    gen_model = model
                    break
                elif verbose and attempt < max_retries - 1:
                    print(f"{prefix}   ↳ got {len(prompt_text)} chars, retrying...")

            if len(prompt_text) < MIN_PROMPT_LENGTH:
                prompt_text = generate_fallback_prompt(node, layer)
                gen_model = "fallback"
                failed += 1

        write_template(output_dir, node, layer, prompt_text, schema, gen_model)
        generated += 1
        status = "✓" if gen_model != "fallback" else "~ (fallback)"
        print(f"{prefix} {status}")

    write_grid_index(output_dir, list(node_map.values()), list(layer_map.values()))

    elapsed = time.time() - start_time
    print()
    print("=" * 60)
    print(f"  COMPLETE")
    print(f"  Generated: {generated} templates")
    if failed:
        print(f"  Fallbacks: {failed}")
    else:
        print(f"  Fallbacks: 0 — all generated by LLM ✓")
    print(f"  Time:      {elapsed:.1f}s ({elapsed/max(generated,1):.1f}s per template)")
    print(f"  Output:    {output_dir}")
    print("=" * 60)

    remaining = find_broken_templates(output_dir)
    if remaining:
        print(f"\n  ⚠  {len(remaining)} templates still under {MIN_PROMPT_LENGTH} chars:")
        for nid, lid in remaining[:10]:
            print(f"      {nid}_{lid}")
        if len(remaining) > 10:
            print(f"      ... and {len(remaining)-10} more")
        print(f"  Run: python generate_grid.py --retry-broken")
    else:
        print(f"\n  ✓ All templates have prompts >= {MIN_PROMPT_LENGTH} chars")

    return generated, failed


# ---------------------------------------------------------------------------
# Seed Review
# ---------------------------------------------------------------------------

SEED_TEMPLATES = [
    ("ANCHOR", "PERCEPTION"),
    ("ECHO", "INTUITION"),
    ("PULSE", "PROCESSING"),
    ("LENS", "MEMORY"),
    ("BEACON", "KNOWLEDGE"),
    ("WEAVE", "INTENTION"),
    ("MIRROR", "NARRATIVE"),
    ("COMPASS", "IDENTITY"),
    ("GATEWAY", "WISDOM"),
]


def print_seeds(output_dir: Path):
    print("\n" + "=" * 60)
    print("  SEED TEMPLATES FOR REVIEW")
    print("=" * 60)
    for node_id, layer_id in SEED_TEMPLATES:
        fid = f"{node_id}_{layer_id}"
        filepath = output_dir / f"{fid}.yaml"
        if filepath.exists():
            print(f"\n{'─' * 60}")
            print(f"  {fid}")
            print(f"{'─' * 60}")
            with open(filepath) as f:
                print(f.read())
        else:
            print(f"\n  ✗ {fid} — NOT FOUND")
    print(f"\n{'=' * 60}")
    print("  Next: create corrections.yaml, then run:")
    print("  python generate_grid.py --regenerate --corrections corrections.yaml")
    print(f"{'=' * 60}")


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(
        description="Arcturian Grid — 81-Channel Template Generator",
    )
    parser.add_argument("--nodes-file", type=Path, default=DEFAULT_NODES)
    parser.add_argument("--layers-file", type=Path, default=DEFAULT_LAYERS)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--model", type=str, default=DEFAULT_MODEL)
    parser.add_argument("--corrections", type=Path, default=None)
    parser.add_argument("--regenerate", action="store_true")
    parser.add_argument("--nodes", type=str, default=None)
    parser.add_argument("--layers", type=str, default=None)
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--show-seeds", action="store_true")
    parser.add_argument("--retry-broken", action="store_true")
    parser.add_argument("--max-retries", type=int, default=3)
    parser.add_argument("--verbose", "-v", action="store_true")

    args = parser.parse_args()

    if args.show_seeds:
        print_seeds(args.output)
        return

    filter_nodes = [n.strip() for n in args.nodes.split(",")] if args.nodes else None
    filter_layers = [l.strip() for l in args.layers.split(",")] if args.layers else None

    generate_grid(
        nodes_path=args.nodes_file,
        layers_path=args.layers_file,
        output_dir=args.output,
        model=args.model,
        corrections_path=args.corrections,
        filter_nodes=filter_nodes,
        filter_layers=filter_layers,
        dry_run=args.dry_run,
        verbose=args.verbose,
        retry_broken=args.retry_broken,
        max_retries=args.max_retries,
    )


if __name__ == "__main__":
    main()
