"""
Handler for component documentation queue tasks.
Generates docs/generated/components/{name}.md
"""
import os
import json
import logging
import psycopg2

from iris.docs.llm import call_llm, build_component_prompt

logger = logging.getLogger("iris.docs.handlers.component")

DOCS_DIR = "/opt/mythos/docs/generated/components"


def handle(task, dry_run=False):
    """
    Process a component_doc task.
    Returns (success: bool, output_path: str or None)
    """
    component = task.get("component", "unknown")
    logger.info(f"Generating component doc: {component}")

    os.makedirs(DOCS_DIR, exist_ok=True)

    # Pull file metadata from Postgres manifest (latest run)
    files_data = _get_component_files(component)
    if not files_data:
        logger.warning(f"No manifest data for component '{component}', using task data")
        files_data = [{"file_path": fp, "line_count": 0, "file_type": "?"} for fp in task.get("files", [])]

    if dry_run:
        logger.info(f"[DRY RUN] Would generate {component}.md from {len(files_data)} files")
        return True, None

    # Generate via LLM
    prompt = build_component_prompt(component, files_data)
    content = call_llm(prompt)

    if not content:
        logger.error(f"LLM returned empty for component '{component}'")
        return False, None

    # Write markdown
    output_path = os.path.join(DOCS_DIR, f"{component}.md")
    with open(output_path, "w") as f:
        f.write(f"# {component}\n\n")
        f.write(f"*Auto-generated by Iris Documentation Worker*\n\n")
        f.write(content)
        f.write("\n")

    logger.info(f"Wrote {output_path}")
    return True, output_path


def _get_component_files(component):
    """Pull file metadata from the latest introspection run."""
    try:
        conn = psycopg2.connect(dbname="mythos")
        with conn.cursor() as cur:
            # Get latest completed run
            cur.execute(
                """SELECT run_id FROM introspection_runs
                   WHERE status = 'completed'
                   ORDER BY finished_at DESC LIMIT 1"""
            )
            row = cur.fetchone()
            if not row:
                return []

            run_id = row[0]
            cur.execute(
                """SELECT file_path, file_type, line_count, size_bytes,
                          llm_summary, llm_purpose, llm_dependencies, llm_issues
                   FROM system_manifest
                   WHERE run_id = %s AND component = %s
                   ORDER BY file_path""",
                (str(run_id), component),
            )
            columns = [desc[0] for desc in cur.description]
            return [dict(zip(columns, row)) for row in cur.fetchall()]
    except Exception as e:
        logger.warning(f"Could not fetch manifest for {component}: {e}")
        return []
    finally:
        try:
            conn.close()
        except Exception:
            pass
