"""Handler for system_map queue tasks."""
import os, logging, psycopg2
from iris.docs.llm import call_llm, build_system_map_prompt

logger = logging.getLogger("iris.docs.handlers.system_map")
DOCS_DIR = "/opt/mythos/docs/generated"


def handle(task, dry_run=False):
    """Process a system_map task. Returns (success, output_path)."""
    logger.info("Generating system map")
    os.makedirs(DOCS_DIR, exist_ok=True)
    components_data = _get_all_components()
    if not components_data:
        logger.warning("No component data, using task data")
        components_data = [{"name": c, "file_count": 0, "total_lines": 0} for c in task.get("components", [])]
    if dry_run:
        logger.info(f"[DRY RUN] Would generate system_map.md from {len(components_data)} components")
        return True, None
    prompt = build_system_map_prompt(components_data)
    content = call_llm(prompt, max_tokens=6144)
    if not content:
        logger.error("LLM returned empty for system map")
        return False, None
    output_path = os.path.join(DOCS_DIR, "system_map.md")
    with open(output_path, "w") as f:
        f.write("# Mythos System Map\n\n*Auto-generated by Iris Documentation Worker*\n\n")
        f.write(content)
        f.write("\n")
    logger.info(f"Wrote {output_path}")
    return True, output_path


def _get_all_components():
    """Pull component stats from latest introspection run."""
    conn = None
    try:
        conn = psycopg2.connect(dbname="mythos")
        with conn.cursor() as cur:
            cur.execute("""SELECT run_id, report_json FROM introspection_runs WHERE status = 'completed' ORDER BY finished_at DESC LIMIT 1""")
            row = cur.fetchone()
            if not row: return []
            run_id, report_json = row
            if report_json and isinstance(report_json, dict):
                comps = report_json.get("components", {})
                result = []
                for name, detail in comps.items():
                    result.append({"name": name, "file_count": detail.get("file_count", 0), "total_lines": detail.get("total_lines", 0), "summary": detail.get("summary", ""), "health": detail.get("health", "")})
                if result: return result
            cur.execute("""SELECT component, COUNT(*), SUM(line_count) FROM system_manifest WHERE run_id = %s GROUP BY component ORDER BY SUM(line_count) DESC""", (str(run_id),))
            return [{"name": r[0], "file_count": r[1], "total_lines": r[2]} for r in cur.fetchall()]
    except Exception as e:
        logger.warning(f"Could not fetch component data: {e}")
        return []
    finally:
        if conn: conn.close()
